sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.075.1
 - dmd-2.074.0
 - ldc-1.2.0

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
