sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.073.2
 - ldc-1.1.0

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
