sudo: false

os:
 - linux

language: d

d:
 - dmd-2.081.1
 - ldc-1.10.0

env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH
